### ISSUE TITLE
[Q] Formatting a cell

### ISSUE THREAD

**Issue by jherault** [jferard/fastods#107]
Hi,

First of all it's not an issue, just questions. I understand if that this issue is immediately closed but I try.

I'm using the library to create ODS files with different types of cells.
I want to set the format of a cell but I don't know how to do it.

Currently, for a date cell type, the ouput format show the hour and minutes of the given date.
How to format the cell with a given format (ex: dd/MM/yyyy only) ?

Idem, how to set an integer value, I can only use a float type and obviously the result is a float... I just want to type the cell with an integer type. 

Thanks a lot.

**Comment by jherault** [comment]
Add a pullrequest instead

**Comment by jferard** [comment]
Hi. This is a good question since this is not possible yet. Everything is (almost) ready to add and use custom formats, but everything is locked (e.g. `setDataStyle` in `TableCellImpl` is `private`). I'll unlock it quickly!

**Comment by jherault** [comment]
Glad to hear it!!! Waiting for updates and samples byt the way ;-)

**Comment by jferard** [comment]
I think it's ok now. See https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java for an example.

**Comment by jherault** [comment]
Hi Julien,

Good Job!!! Is the library with this feature on maven central ?

Thx


--
Jérémy

**Comment by jferard** [comment]
Not yet, but I'm working on the 0.6.0 version.

**Comment by jferard** [comment]
@jherault Now on oss.sonatype.org, tomorrow on maven central!

**Comment by jherault** [comment]
Really nice and thank you!!! 
I've updated my dependency on your project and I can do what I want to format the displayed value.
An other enhancement would be on date again, to not force the format of the value to `TableCellImpl.DATE_VALUE_FORMAT` because users are "shocked" to see the hours in the value field.
To bypass that, I've done something like this:
```
dataCell.setDateValue(aDate);
dataCell.setDataStyle(dateStyle);
Field valueField = TableCellImpl.class.getDeclaredField("value");
valueField.setAccessible(true);
valueField.set(dataCell, new SimpleDateFormat("yyyy-MM-dd").format((Date) value));
```
It works like a charm, but... 

Best,
Jeremy

**Comment by jferard** [comment]
I'll have a look at this...

**Comment by jferard** [comment]
I believe you don't need reflection here. This should fulfill your needs:

    final DataStylesBuilder dsb = DataStylesBuilder.create(Locale.FRANCE); // Poitiers!
    dsb.dateStyleBuilder().dateFormat(
        new DateStyleFormat(DateStyleFormat.LONG_YEAR, DateStyleFormat.DASH,
              DateStyleFormat.MONTH, DateStyleFormat.DASH, DateStyleFormat.DAY)).build()
    );
    final DataStyles ds = dsb.build();
    final AnonymousOdsFileWriter writer = this.odsFactory.dataStyles(ds).createWriter();
    final OdsDocument document = writer.document();
    ...
    dataCell.setDateValue(aDate);

See https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java#L98 and https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java#L166

Note: `TableCellImpl.DATE_VALUE_FORMAT` is just the internal format for OpenDocument 1.2 (see 19.370, 18.3.14 and https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dateTime).

**Comment by AhmedAli1050** [comment]
Still getting the same issue, showing date with time like 01/14/2024 09:00:00/ 01/01/2018 09:00:00
and how can we show only date instead of time

cal.set(2017, 12, 1, 0, 0, 0);
        walker.setDateValue(cal);
        // Add a custom format
        final DataStyle dateStyle = new DateStyleBuilder("custom-date-datastyle", Locale.US)
                .dateFormat(
                        new DateTimeStyleFormat(DateTimeStyleFormat.DAY, DateTimeStyleFormat.DOT,
                                DateTimeStyleFormat.MONTH, DateTimeStyleFormat.DOT,
                                DateTimeStyleFormat.YEAR)).visible().build();
        walker.setDataStyle(dateStyle);
        walker.next();
