### ISSUE TITLE
[FRENCH] Soucis de couleur de bordure lors de l'utilisation de FloatValue de la classe TableCell

### ISSUE THREAD

**Issue by MatthieuChvllr** [jferard/fastods#122]
Bonjour,

Je me permet de vous contacter suite à un soucis lors de l'utilisation de la méthode FloatValue de la classe TableCell.

En effet, afin de générer mon fichier ODS, je déclare un TableCellStyle 
```
        TableCellStyle styleTableau = TableCellStyle.builder("styleTableau").borderAll(SimpleLength.mm(0.15),
            Color.BLACK, BorderAttribute.DEFAULT_STYLE).build();
```
J'applique celui-ci à mon objet TableTow : 
```
        TableRow row = table.nextRow();
        row.setDefaultCellStyle(styleTableau);
```
Ensuite j'alimente mon objet row comme ceci : 
 row.getOrCreateCell(EnumFichierODS.MONTANT.getPosition()).setFloatValue(montantTotal);

Or lors de la génération du fichier, je constate qu'autour des cellules alimentées par la méthode FlotValue, les bordures sont blanches.

Pouvez-vous m'indiquer comment forcer les bordures noires lors de l'utilisation de la méthode FloatValue.

Merci,

Cordialement,

CHEVALLIER Matthieu

**Comment by jferard** [comment]
Bonjour,

Je viens de réaliser un rapide test avec la version en cours de développement:
```
        final TableCellStyle tableStyle = TableCellStyle.builder("tableStyle")
                .borderAll(SimpleLength.mm(0.15), SimpleColor.BLACK, BorderAttribute.DEFAULT_STYLE)
                .build();
        row = table.nextRow();
        row.setDefaultCellStyle(tableStyle);
        row.getOrCreateCell(5).setFloatValue(100.0);
```
Le résultat est le suivant:

![cap-fastods](https://user-images.githubusercontent.com/10564095/41120666-797954f0-6a96-11e8-8c26-cd9893809e67.png)

*A priori*, aucune différence sur ce point depuis la version 0.6.0 disponible sur le central maven (https://mvnrepository.com/artifact/com.github.jferard/fastods/0.6.0), donc ça devrait fonctionner avec la version 0.6.0. Quelle version utilisez-vous ?

(Je vais faire des tests plus poussés ce week-end...)

**Comment by MatthieuChvllr** [comment]
Bonjour,

Du coup, je me suis mis en 0.6.0 car ma version était 0.4.1.

Cependant, je rencontres un nouveau soucis au niveau de la taille des colonnes ^^'
Je souhaites définir une taille pour chacune de mes colonnes grâce à ce code : 
```
        // Création des entêtes de colonnes
        final TableRow row = table.nextRow();
        for (int index = 0; index < colonnes.length; index++)
        {
            table.setColumnStyle(index, TableColumnStyle.builder("styleColonne" + index).columnWidth(
                SimpleLength.cm(Double.parseDouble(colonnes[index][1]))).build());

            TableCell cell = row.getOrCreateCell(index);
            cell.setStringValue(colonnes[index][0]);
            cell.setStyle(styleEntete);
        }
```
Ensuite l'alimentation des row.

Or lors de la génération du fichiers, je constates que la taille des différents colonnes est toujours la même est assez petite (2.26 cm).

Existe-t-il un moyen d'auto fixer la taille des colonnes suivant le contenu de celle-ci ?

Merci,

Cordialement,

**Comment by jferard** [comment]
Bonjour,

Deux points:

1. Avec **`buildHidden()`** à la place de `build()` dans la ligne 

```
table.setColumnStyle(index, tableColumnStyle.builder("styleColonne" + index)
.columnWidth(SimpleLength.cm(Double.parseDouble(colonnes[index][1])))
.build());
```

le style de colonne est pris en compte. Evidemment, il n'y a pas moyen de deviner cela. Je suis en train de supprimer la méthode `buildHidden`: la méthode `build` doit en théorie faire le bon choix. Mais ce n'est pas le cas pour l'instant pour les colonnes : je ferai la correction dans la version 0.6.1.

2. Le format Open Document possède une option `style:use-optimal-column-width`, mais qui n'est pas reconnue par LibreOffice/OpenOffice. Lorsqu'on utilise "Largeur de colonne optimale", l'application parcourt toutes les cellules afin de déterminer la largeur optimale (voir https://github.com/jferard/fastods/issues/95 et https://github.com/jferard/fastods/issues/96 pour plus d'explications). Je n'ai pas prévu pour l'instant d'outil pour faire ce calcul de largeur optimale à la manière LO/OO, et cela serait peut-être impossible dans certains cas.

**Comment by jferard** [comment]
Voir https://github.com/jferard/fastods/issues/123. A partir de la v 0.6.1, `build` sera suffisant.

**Comment by MatthieuChvllr** [comment]
Bonjour,

Merci de votre réponse.
En utilisant la méthode buildHidden(), la taille des colonnes indiquée est respectée.

En ce qui concerne la taille, j'en ai positionné une en estimant un max en attendant la possibilité d'une valeur optimal.

Je ferme l'issue.

Cordialement,
