### ISSUE TITLE
[FRENCH] Soucis filtre en-tête colonne avec plusieurs onglets

### ISSUE THREAD

**Issue by MatthieuChvllr** [jferard/fastods#124]
Bonjour,

Tout d'abord, je voudrais vous remercier pour le travail fourni afin de nous fournir l'outil FastODS.
En effet, nous utilisions JasperReport qui avait le désavantage d'être long à la génération et fastidieux lors de la modification des fichiers (passage par template, ...). 

Votre outil est très rapide à la génération (quasi instantané) et la création/modification d'un fichier est très simple avec les moyens mis à la disposition de l'utilisateur.
Seul mini-bémol, une documentation mais j'ai pu constaté que vous étiez réactif lors qu'on vous ouvre une issue donc très petit bémol.

Je suis en cours de migré la génération des fichiers vers FastODS en 0.6.0 et je rencontre un petit lors de l'ajout d'un filtre dans les en-têtes lors que le document comporte plusieurs onglets (cela marche très bien avec un seul onglet).

Voici le code que j'ai mis en place : 

```
        String nomFichier = matricule + NOM_FICHIER + formatterSimple.format(dateTraitement.getTime()) + "_"
            + formatterComplet.format(new Date()) + ".ods";

        File fichier = new File(dossierSortie.getAbsolutePath() + File.separator + nomFichier);

        final OdsFactory odsFactory = OdsFactory.create();
        final AnonymousOdsFileWriter writer = odsFactory.createWriter();
        final OdsDocument document = writer.document();
		
		/**
         * ONGLET FORM1
         */
        // génération de l'objet Table
        final Table tableForm1 = ODSExportUtile.genererTable(document, ONGLET_FORM1, COLONNES_ONGLET_FORM_1);
        int nbLigneForm1 = valoriserFichierOngletForm1(matricule, tableForm1);
		
		/**
         * ONGLET FORM2
         */
        // génération de l'objet Table
        final Table tableForm2 = ODSExportUtile.genererTable(document, ONGLET_FORM2, COLONNES_ONGLET_FORM_2);
        int nbLigneForm2 = valoriserFichierOngletForm2(matricule, tableForm2);
		
		// Ajout des auto-filtre
        document.addAutofilter(tableForm1, 0, 0, nbLigneForm1 - 1, COLONNES_ONGLET_FORM_1.length - 1);
        document.addAutofilter(tableForm2, 0, 0, nbLigneForm2 - 1, COLONNES_ONGLET_FORM_2.length - 1);
		
		writer.saveAs(fichier);
```
Cependant lors de la génération, les filtres ne sont pas présents ....

Pouvez-vous me confirmer que le code utilisé est correct (il fonctionne pour un onglet).

Merci de votre analyse,

Cordialement,

**Comment by jferard** [comment]
Bonjour,

Concernant la documentation, c'est un gros travail et je préfère pour l'instant ajouter des exemples 
 dans le dossier https://github.com/jferard/fastods/tree/master/fastods/src/test/java/com/github/jferard/fastods/it car ces exemples servent également de test. Je suis ainsi certain que les exemples restent constamment à jour car l'API est encore changeante et le maintien d'une documentation complète serait trop lourd. Lorsque l'API sera fixée, à la version 1.0.0, je rédigerai une documentation.

Je viens de tester le code ci-dessus (avec deux tables toutes simples) et celà fonctionne... sauf quand le nom de la table contient un espace, un guillemet ou un point. Est-ce que cela est le cas chez vous ?

Merci pour vos remarques !

**Comment by MatthieuChvllr** [comment]
Bonjour,

Désolé pour le temps de réponse mais congés oblige :)

Comme conseillé, j'ai supprimer les espaces dans les noms des onglets et filtres sont bien présents lors de la génération. Merci !

A noter que j'ai observé 2 comportements que vous avez sans doute dû voir/corriger : 
- lors de la présence du caractère "/" dans l'onglet, le nom n'est pas pris en compte et est remplacé par "feuille..".
- lors de la présence du caractère "&" dans l'onglet, le fichier s'ouvre en erreur.

Je ferme l'issue vu que l' "anomalie" initiale est corrigée.

Merci de votre travail.

Cordialement,
