### ISSUE TITLE
[FRENCH] [OPTIONNEL] Précision d'un nombre dans une cellule

### ISSUE THREAD

**Issue by MatthieuChvllr** [jferard/fastods#134]
Bonjour,

Je me permets d'ouvrir un nouvel issue afin de savoir s'il est possible de définir la précision d'un chiffre après la virgule lors de sa valorisation dans une cellule.

En effet, j'ai une colonne "nbInstument" que je valorise grâce à la méthode `setFloatValue` afin qu'elle devienne "calculable" (addition quand on sélectionne plusieurs lignes par LibreOffice).

Cependant, l'affichage dans LibreOffice m'affiche par exemple 4,00 alors que je souhaiterais 4.

Ce comportement est-il possible ?

Merci,

Cordialement,

**Comment by jferard** [comment]
Bonjour,

[Cet exemple](https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java#L147) montre comment appliquer un "data style" à une cellule contenant un float. En principe cela doit convenir, mais si ça ne suffit pas, j'ai besoin d'un exemple précis pour faire les éventuelles corrections (code + affichage souhaité + affichage réel).

Cordialement.

**Comment by jferard** [comment]
I'm closing this issue since I did not get any feedback in 6 months.
