### ISSUE TITLE
[FRENCH] - Ombre verticale tooltip reste affichée

### ISSUE THREAD

**Issue by Max4409** [jferard/fastods#135]
Salut,

je suis en 0.6.0, pour info, et j'ai un bug mineur sur le tooltip: 

row.getOrCreateCell(index).setTooltip("monTooltip");

L'affichage est OK mais quand il disparaît, l'ombre verticale à droite reste affichée. Un clic sur les cellules sur lesquelles le tooltip apparait en surimpression la fait disparaitre.

Merci par avance.

**Comment by jferard** [comment]
Salut,

A priori, c'est un problème au niveau LibreOffice/OpenOffice. Un moyen simple de le vérifier:

1. ouvrir le document
2. ajouter un espace dans une cellule vide
3. enregistrer le document.
4. fermer le document

Le document est maintenant au format ODS variante LibreOffice. Essaie ensuite de le rouvrir pour voir si le problème persiste. 

Si c'est le cas, il y a très fort à parier que c'est un problème LO (et dans ce cas il peut être intéressant de tester le fichier original avec une autre version de LO).

Sinon je peux examiner le code et le fichier qui posent problème (un exemple minimal, anonymisé si nécessaire).

**Comment by Max4409** [comment]
J'ai fait le test et le problème subsiste. Je vais donc essayer avec d'autres versions.
Merci pour ton temps et ton aide.

**Comment by jferard** [comment]
Seems fixed.
