### ISSUE TITLE
Freezing rows and columns in document

### ISSUE THREAD

**Issue by denixx** [jferard/fastods#143]
Hi!
Made a search with Google query "freeze row site:https://github.com/jferard/fastods" and found nothing.

Take a look at these articles of LO and OO:
https://help.libreoffice.org/Calc/Freezing_Rows_or_Columns_as_Headers
https://wiki.openoffice.org/wiki/Documentation/OOoAuthors_User_Manual/Getting_Started/Freezing_rows_and_columns

Could I freeze at least first row programmatically with existing latest sources (maybe I could use some custom XML-strings to build a custom style or something like this), or should I ask for a feature request?

This feature is too cool for data dumps to fix a header and make it always visible.

**Comment by jferard** [comment]
Hi. Not implemented yet, but it's a good idea. I'll have a look at this.

**Comment by jferard** [comment]
This is not part of the ODF specs, but "ODF Consumer dependant" (LibreOffice or OpenOffice are ODF Consumers, while FastODS is an ODF Producer).

When I save a file with LO, in "settings.xml", Views/Tables/[table name], I have the relevant config-items:

    <office:settings>
        <config:config-item-set config:name="ooo:view-settings">
            <config:config-item-map-indexed config:name="Views">
                <config:config-item-map-entry>
                    <config:config-item config:name="ViewId" config:type="string">view1</config:config-item>
                    <config:config-item-map-named config:name="Tables">
                        <config:config-item-map-entry config:name="[table name]">
                            <config:config-item config:name="VerticalSplitMode" config:type="short">number of frozen rows</config:config-item>
                            <config:config-item config:name="HorizontalSplitPosition" config:type="int">number of frozen cols</config:config-item>

Those items are accessible to FastODS via the `SettingsElement` object. The code:

    ConfigItemMapEntry tableConfig = ConfigItemMapEntrySequence.create("<table name>");
    tableConfig.add(new ConfigItem("HorizontalSplitPosition", "int", "1"));
    tableConfig.add(new ConfigItem("VerticalSplitPosition", "int", "1"));
    settingsElements.addTableConfig(tableConfig);

But the `addTableConfig` method is currently not accessible through `OdsDocument` interface (whereas the `setViewSetting` is). I need a little time to think about it, but it's technically easy to add the path from `OdsDocument` to the tables configs.

Roadmap:

* add `addTableConfig` to `OdsDocument`
* add a `freezeCells` methods to `tool/TableHelper`

**Comment by jferard** [comment]
Example code:

    Logger logger = Logger.getLogger("...");
    Locale locale = Locale.US;
    OdsFactory odsFactory = OdsFactory.create(logger, locale);
    final AnonymousOdsFileWriter writer = odsFactory.createWriter();
    final OdsDocument document = writer.document();
    Table table = document.addTable(name);
    ...
    document.freezeCells(table, 1, 1);
    writer.saveAs("...");

Please reopen the issue if this doesn't work as expected.

**Comment by ashitikov-bld** [comment]
@jferard It seems that rows and columns are mixed up
![image](https://user-images.githubusercontent.com/49314547/64112346-cd4e7800-cd8f-11e9-96ea-15cfffa43dc7.png)
![image](https://user-images.githubusercontent.com/49314547/64112430-0d155f80-cd90-11e9-8a29-ec0ddc14e514.png)

**Comment by jferard** [comment]
You are right. I'll fix it soon.

**Comment by ideas-into-software** [comment]
Attempt to freeze header row via `document.freezeCells(table, rowCount, colCount)`, where `colCount` is equal to number of columns in a given sheet, does not work as expected.

Please see attached short screencast, as well as screenshot and example documents (‘testExport.programmatic-header-freeze-problem.ods’, ‘testExport.manual-header-freeze.ods’).

I would expect same result as that obtained by freezing header row manually (see attached ‘testExport.manual-header-freeze.ods’).

Including @stbischof as per his request.


![Screenshot from 2023-02-10 21-50-25](https://user-images.githubusercontent.com/9023040/218274957-d0d2f133-49b5-4074-8445-5792796a2e08.png)

https://user-images.githubusercontent.com/9023040/218274958-6c140401-b7a2-416f-bd78-69182b3d39d2.mp4

[testExport.manual-header-freeze.ods](https://github.com/jferard/fastods/files/10714439/testExport.manual-header-freeze.ods)
[testExport.programmatic-header-freeze-problem.ods](https://github.com/jferard/fastods/files/10714440/testExport.programmatic-header-freeze-problem.ods)

**Comment by jferard** [comment]
Hello. thanks for reporting. It seems that, in settings.xml, `PositionBottom` should have the same value as `VerticalSplitPosition` and `PositionRight` the same value as `HorizontalSplitPosition`. I'm investigating.

**Comment by denixx** [comment]
Hello, Julien.
I had the same experience with this functionality when it appeared, but for me, it was a file, generated and sent to email.
As I understand, Google Docs preview in email fixed the issue with fixed rows and they looked good in emails.

**Comment by jferard** [comment]
Thanks @denixx for the information.
