### ISSUE TITLE
setStringValue is not handled correctly

### ISSUE THREAD

**Issue by uwekoenig** [jferard/fastods#148]
The method _setStringValue_ does not set the cell style to the correct value. 
If I want to insert **1020 023/3** as text I would expect to get the value like given and the cell style **Text**. But the result is **'1020 023/3** (with leading abostroph) and cell style **Decimal** which causes problems for me.
The same happens if I use _setObjectValue_.

Do I do something wrong or is it a fault?

**Comment by jferard** [comment]
@uwekoenig 
> f I want to insert 1020 023/3 as text I would expect to get the value like given and the cell style Text. But the result is '1020 023/3 (with leading abostroph)

The leading quote does not seem to be a bug: https://ask.libreoffice.org/en/question/86199/how-to-remove-single-quote-in-front-of-numbers-in-a-cell/. I think it's displayed because your string is similar to a number, but I'll check.

>  and cell style Decimal which causes problems for me.

Can you elaborate on the `Decimal` cell style? I had some issues with data style and this may be a new one. Can you post a example?

> The same happens if I use setObjectValue.

`setObjectValue` is a wrapper for `setCellValue(CellValue.fromObject(object));`. `CellValue.fromObject(object)` tries to guess what your (java) Object may be in LibreOffice "world": a date, a float, a boolean, ...? By definition, if you know what your object is, you should use a specific method (`setDateValue`, `setFloatValue`, `setBooleanValue`, ...)

**Comment by uwekoenig** [comment]
@jferard 
Thank you for your feedback. The leading abostroph is a problem for me because formulas like VLOOKUP do not work if **1020 023/3** and **'1020 023/3** (Point 2 in the screenshot) is compared.

> Can you elaborate on the Decimal cell style? I had some issues with data style and this may be a new one. Can you post a example?

Sorry I made a mistake when I translated to English. Switched the language of the UI now and there the Cell type is called **Number** (Point 3 in the screenshot).

![2019-05-28 13_12_08-Export_2019-05-28T12_12_20 089 ods - LibreOffice Calc](https://user-images.githubusercontent.com/23554459/58474231-d4d80280-814a-11e9-8624-b42dfb66b818.png)

What I am looking for is to set Cell type **Text** (Point 4 in the screenshot).

**Comment by jferard** [comment]
I had some time to investigate. With LO 6.0.7.3 (Ubuntu 18.04) and the following code:

        OdsFactory odsFactory = OdsFactory.create();

        final AnonymousOdsFileWriter writer = odsFactory.createWriter();
        final OdsDocument document = writer.document();

        Table table = document.addTable("Sheet");

        TableRow row = table.getRow(0);
        TableCell cell = row.getOrCreateCell(0);
        cell.setStringValue("1020 023/3");

        writer.saveAs(new File("./generated_files", "mysheet0.ods"));

I can reproduce your output:

![Capture du 2019-05-30 10-21-31](https://user-images.githubusercontent.com/10564095/58619247-cf062c80-82c4-11e9-993c-c50e6b8e2382.png)

First, it's clear that the *display format* should not be `number` but `text`. **This is a bug** (thank you for pointing out).
Second, I think this a no effect on `VLOOKUP`. I added manually some values in the cells:

The original cell:
![Capture du 2019-05-30 10-15-38](https://user-images.githubusercontent.com/10564095/58619627-8c911f80-82c5-11e9-9f0d-c6ea25857e6f.png)

A cell with the same content but formatted as text:
![Capture du 2019-05-30 10-17-46](https://user-images.githubusercontent.com/10564095/58619663-9d419580-82c5-11e9-9884-79f9ee25ab46.png)

And the `VLOOKUP`:
![Capture du 2019-05-30 10-16-33](https://user-images.githubusercontent.com/10564095/58619712-b64a4680-82c5-11e9-8e64-0e302b1f75d2.png)

Did you try to create a `VLOOKUP` programmatically? If so, can you post the relevant code?

**Comment by jferard** [comment]
Curiously, LO seems to create text cells with the `number` display format. This file was created manually (no FastODS intervention):

![Capture du 2019-05-30 11-20-16](https://user-images.githubusercontent.com/10564095/58622910-109ad580-82cd-11e9-92c1-17b2d88e4a1e.png)

You can see that the display is `number`. The generated XML is:

    <table:table table:name="Sheet1" table:style-name="ta1"><table:table-column table:style-name="co1" table:default-cell-style-name="Default"/>
		<table:table-row table:style-name="ro1">
			<table:table-cell office:value-type="string" calcext:value-type="string">
				<text:p>102</text:p>
			</table:table-cell>
		</table:table-row>
		<table:table-row table:style-name="ro1">
			<table:table-cell office:value-type="string" calcext:value-type="string">
				<text:p>one hundred and two</text:p>
			</table:table-cell>
		</table:table-row>
	</table:table>

It seems that the default data style is `number`. You never see the issue in LO because if you type a number (or a string with digits) it becomes a decimal (type, not display). I tried to type `1020 023/3` and it became `1023023`.

My idea is that (*if you can confirm that `VLOOKUP` works as I think it should*) I should let the user set the `text` display format if the quote *should not* be displayed. (This will be explained in `setStringValue`)

**Comment by uwekoenig** [comment]
Thank you for testing all these cases. You are right that the VLOOKUP works with or without the apostrophe in case of cell type Number or Text.
Nevertheless it would be good if there would be the possibility to set the cell type to TEXT by code. Our users start working with these data in Calc after exporting from our system. If they copy from one file to the generated file and Paste Unformated Text the problems begin if the cells are not formatted correctly and the quantity of data sets is big enough that do not recognise it immediately. In that case Calc replaces e.g. **1020 023/3** by **1027 2/3** (or as decimal 1027,66666666667).
Maybe it would be the best to offer two different kind of setStringValue methods because I can imagine that other developers would like to get the current behaviour for their scenarios. An additional method **setStringValueAsText** could be the generic solution.

**Comment by uwekoenig** [comment]
An alternative could be to control it by some kind of TableCellStyle (or DataStyle )but I could not find a way to do it with the current implementation.

**Comment by jferard** [comment]
**Feel free to reopen if necessary.**

The `TextStyle` data style was missing. I just created it. You can try:

        cell.setStringValue("1020 023/3");
        TextStyle text = new TextStyleBuilder("text0", Locale.US).build();
        cell.setDataStyle(text);

Output:

![Capture du 2019-06-03 20-50-32](https://user-images.githubusercontent.com/10564095/58826562-416a6a00-8641-11e9-8ac9-a928e3c3a944.png)

(No more quote!)

If you need to add a preamble:

        cell.setStringValue("1020 023/3");
        TextStyle text = new TextStyleBuilder("text0", Locale.US).text("<number:text>My text: </number:text><number:text-content/>").build();
        cell.setDataStyle(text);

Output: 

![Capture du 2019-06-03 20-46-31](https://user-images.githubusercontent.com/10564095/58826345-ce60f380-8640-11e9-8de0-79451dea759e.png)

As you see, the style adds `My text: ` before the actual text, but the content is "1020 023/3").

**Comment by uwekoenig** [comment]
Looks perfect. Thank you very much Julien.
Could you update the Maven version to allow using it easily by setting the correct verison number in the pom.xml?

**Comment by jferard** [comment]
You are welcome. The Maven repo will be updated soon.

**Comment by jferard** [comment]
Maven repo updated!

**Comment by uwekoenig** [comment]
Tested it just now. Works like a charm. Thank you so much.
