### ISSUE TITLE
Some issue in class MacroLibraryTest

### ISSUE THREAD

**Issue by JulianotCosta** [jferard/fastods#178]
Hello,
There is some issue I am not able to fix.

Error:(35, 44) java: constructor Capture in class org.easymock.Capture<t> cannot be applied to given types;
required: org.easymock.CaptureType
found: no arguments
reason: actual and formal argument lists differ in length

my pom.xml file is

<dependency>
<groupid>org.easymock</groupid>
<artifactid>easymock</artifactid>
<version>4.1</version>
</dependency>

looks like this piece of code is work

@Test public void testAdd() throws IOException {
final OdsDocument document = PowerMock.createMock(OdsDocument.class);
final MacroLibrary lib = new MacroLibrary("ml", false, Arrays.asList(this.module));
final Capture <stringbuilder> sb1 = new Capture <stringbuilder>();
final Capture<charsequence> sb2 = new Capture<charsequence>();

Is there something I need to do to work?

Thank you

**Comment by jferard** [comment]
Hi @JulianotCosta. When do you have this issue? When compiling FastODS (which version?) or when you are writing your own tests? Or is this a EasyMock version conflict in a maven project?

1) If this is a FastODS compilation issue, [current code](https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/util/MacroLibraryTest.java#L39) is different from what you wrote:

```
    @Test
    public void testAdd() throws IOException {
        final OdsDocument document = PowerMock.createMock(OdsDocument.class);
        final MacroLibrary lib = new MacroLibrary("ml", false, Arrays.asList(this.module));
        final Capture<StringBuilder> sb1 = Capture.newInstance();
        final Capture<byte[]> bs = Capture.newInstance();
        ...
    }
```

You should update to FastODS 7.2.

2) If you are writing your own tests, this seems an issue with EasyMock usage. `Capture` constructors are now private.

3) If this is a maven project conflict, [I just updated the pom](https://github.com/jferard/fastods/commit/6c50164baeeae0105805a11b30cf4faeda18662a) to use the version 4.1 of EasyMock. You can clone the last snapshot.

**Comment by JulianotCosta** [comment]
Hello, Julien!

First of all, thank you for answering my message.
Just to brief you, I am trying to create a code in Java to create and write spreadsheet in OpenOffice format (.ods). So, this spreadsheet should have some data in different tabs.  

My first step is trying to create an .ods file with this java code:

`
package br.com.oracle.retail.rfm.automation.Induction;


import com.github.jferard.fastods.AnonymousOdsFileWriter;
import com.github.jferard.fastods.OdsDocument;
import com.github.jferard.fastods.OdsFactory;
import com.github.jferard.fastods.Table;
import com.github.jferard.fastods.TableCell;
import com.github.jferard.fastods.TableRowImpl;



import java.io.File;
import java.io.IOException;
import java.util.Locale;
import java.util.logging.Logger;

/**
 * The section 1 of the tutorial
 *
 * @author J. Férard
 */
class A_HelloWorld {
    /**
     * @throws IOException if the file can't be written
     */
    static void example() throws IOException {
        // >> BEGIN TUTORIAL (directive to extract part of a tutorial from this file)
        // # Hello, world!
        //
        // Let's start with the famous "Hello, World!" example.
        //
        // As stated in the javadoc, "An OdsFactory is the entry point for creating ODS documents."
        // Every time you want to create an ODS document, you'll start with something like that:
        final OdsFactory odsFactory = OdsFactory.create(Logger.getLogger("hello-world"), Locale.US);

        // Now, you can create an ODS writer. You have the choice: either you give the filename
        // now, or you keep it for the end. Let's create an anonymous writer: the content will live
        // in memory until we save it to a file:
        final AnonymousOdsFileWriter writer = odsFactory.createWriter();

        // The writer owns a document that we need to create a spreadsheet:
        final OdsDocument document = writer.document();

        // Okay, let's go. We create a new table (a new sheet indeed) named "hello-world":
        final Table table = document.addTable("hello-world");

        // We get the first row:
        final TableRowImpl row = table.getRow(0);

        // And the first cell of the first row:
        final TableCell cell = row.getOrCreateCell(0);

        // Note that we could have chained the calls:
        // `TableCell cell = document.addTable("hello-world").getRow(0).getOrCreateCell(0)`
        //
        // Finally, we put the famous sentence in this cell A1
        cell.setStringValue("Hello, world!");

        // And save the file.
        writer.saveAs(new File("generated_files", "a_hello_world_example.ods"));

        // With a `mvn clean verify` at the root of the project, you can check the result in the
        // `fastods-examples/generated-files` directory.
        // << END TUTORIAL (directive to extract part of a tutorial from this file)
    }




    public static void main(String[] args) throws IOException {
        example();
    }

}
`
During build, these errors happens

Information:java: Multiple encodings set for module chunk RFMAutomation "windows-1252" will be used by compiler
Information:java: Errors occurred while compiling module 'RFMAutomation'
Information:javac 1.8.0_211 was used to compile java sources
Information:Module "RFMAutomation" was fully rebuilt due to project configuration/dependencies changes
Information:30/12/2019 14:46 - Build completed with 5 errors and 100 warnings in 28 s 553 ms
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\it\DataStyleExampleIT.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\it\MergeExampleIT.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\it\ReadmeExampleIT.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\it\StyleExampleIT.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods-examples\src\main\java\com\github\jferard\fastods\examples\B_AccessingTablesRowsAndCells.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\main\java\com\github\jferard\fastods\AnonymousOdsDocument.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\main\java\com\github\jferard\fastods\CommonOdsDocument.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\main\java\com\github\jferard\fastods\TableCellWalker.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\main\java\com\github\jferard\fastods\NamedOdsDocument.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\main\java\com\github\jferard\fastods\tool\OdsFileHelper.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\OdsDocumentTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\AnonymousOdsFileWriterTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\it\OdsFileCreationIT.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\LinkTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\NamedOdsDocumentTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\ref\CellAddressParserTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\ref\LocalCellAddressParserTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\ref\RangeAddressParserTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\ref\TableNameUtilTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\RowCellWalkerImplTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\RowsFlusherTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\style\TableColumnStyleTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\style\TableRowStyleTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\TableBuilderTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\TableCellWalkerTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\TableTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\tool\OdsDocumentHelperTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\util\FileOpenResultTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\util\MacroLibraryContainerTest.java
Error:(19, 44) java: constructor Capture in class org.easymock.Capture<T> cannot be applied to given types;
  required: org.easymock.CaptureType
  found: no arguments
  reason: actual and formal argument lists differ in length
Error:(20, 42) java: constructor Capture in class org.easymock.Capture<T> cannot be applied to given types;
  required: org.easymock.CaptureType
  found: no arguments
  reason: actual and formal argument lists differ in length
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\util\MacroLibraryTest.java
Error:(36, 45) java: constructor Capture in class org.easymock.Capture<T> cannot be applied to given types;
  required: org.easymock.CaptureType
  found: no arguments
  reason: actual and formal argument lists differ in length
Error:(37, 43) java: constructor Capture in class org.easymock.Capture<T> cannot be applied to given types;
  required: org.easymock.CaptureType
  found: no arguments
  reason: actual and formal argument lists differ in length
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\util\MacroModuleTest.java
Error:(25, 43) java: constructor Capture in class org.easymock.Capture<T> cannot be applied to given types;
  required: org.easymock.CaptureType
  found: no arguments
  reason: actual and formal argument lists differ in length
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\test\java\com\github\jferard\fastods\util\UniqueListTest.java
D:\GIT_REP\RFMAutomation\fastods-fastods-parent-0.7.0\fastods\src\main\java\com\github\jferard\fastods\util\FastFullList.java

**Comment by jferard** [comment]
Okay. You took the code of a unit test. That's not the best start!

Have a look at the [tutorial](https://github.com/jferard/fastods/wiki/Tutorial). All the examples come from the [fastods-examples module](https://github.com/jferard/fastods/tree/master/fastods-examples/src/main/java/com/github/jferard/fastods/examples) so you can easily copy paste what you need.

Start with the "hello world" example and then try to add new data, tabs, styles...

*note*: EasyMock is a testing framework, but is not needed to compile a project (FastODS does not have any external dependency). Your pom should look like:

    <dependencies>
        <dependency>
            <groupId>com.github.jferard</groupId>
            <artifactId>fastods</artifactId>
            <version>0.7.2</version>
        </dependency>
        ...
