### ISSUE TITLE
Special char µ is written as \uFFFD

### ISSUE THREAD

**Issue by uwekoenig** [jferard/fastods#179]
When I try to write the sign **µ**  in a cell I get as result **\uFFFD** instead (opened with LibreOffice).

**Comment by jferard** [comment]
This is the unicode "REPLACEMENT CHARACTER" (https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character). Might be FastODS or not, I will check..

**Comment by jferard** [comment]
Here's my test code:

        final OdsFactory odsFactory = OdsFactory.create(Logger.getLogger("issue-179"), Locale.US);
        final AnonymousOdsFileWriter writer = odsFactory.createWriter();
        final OdsDocument document = writer.document();
        final Table table = document.addTable("issue-179");
        final TableCellWalker walker = table.getWalker();
        String s = "This is a µ";
        walker.setStringValue(s);
        walker.next();
        walker.setStringValue(Arrays.toString(s.getBytes("UTF-8")));
        String t = "And this is a μ";
        walker.nextRow();
        walker.setStringValue(t);
        walker.next();
        walker.setStringValue(Arrays.toString(t.getBytes("UTF-8")));
        writer.saveAs(new File("generated_files", "issue-179.ods"));


And here's the output:

![issue-179](https://user-images.githubusercontent.com/10564095/73779496-16ff1c80-478d-11ea-8bb8-b2a583b4ac71.png)

As you see, first one is \xc2\xb5 (MICRO SIGN) and second one is \xce\xbc (GREEK SMALL LETTER MU), same symbol but semantic is different.

My guess is that your *source file* is not encoded in utf-8 and when the conversion is made, μ in your encoding is converted to bytes and written to the file. When LibreOffice opens the file, the   REPLACEMENT CHARACTER is used to handle a non utf-8 sequence. Illustration in Python:

```
>>> 'µ'.encode("cp1252")
b'\xb5'
>>> _.decode("utf-8", "replace") # would fail without replace
'�'
>>> ascii(_)
"'\\ufffd'"
```

Please check your source file encoding.

**Comment by uwekoenig** [comment]
You are right. The problem came from another library. Sorry for that.
