### ISSUE TITLE
Add OSGi Support

### ISSUE THREAD

**Issue by juergen-albert** [jferard/fastods#188]
I'd like to provide a PR to add OSGi support. The only change would be an added plugin to your maven build, so it generates the necessary Manifest. Would you accept such a change?

**Comment by jferard** [comment]
Thanks for the proposal. I'm not very familiar with OSGi, so I have a few questions. Does this have any effect on "regular" uses of the library? On the compilation (will `mvn clean install` work as usual?).
It seems the packaging should be `bundle`: this is not one of the "core packaging values" (https://maven.apache.org/pom.html#packaging), could this be an issue?

**Comment by juergen-albert** [comment]
A bundle is  just a normal jar with some additional Metadata in its Manifest. As long as nobody writes OSGi specific code, nothing will change for anybody using the jar. 

I've seen that some bundles have this `bundle` packaging, but I've no idea why they do it. Thus nothing would change. Maven would work as before and only the Manifest would look different. If you decide at a certain point to manually add something to the Manifest, you would need to use the bnd-maven-plugin, that is doing the manifest generation then.

**Comment by jferard** [comment]
Seems okay. Please provide your pull request.

**Comment by juergen-albert** [comment]
I hope to find the time for it over the weekend.
