### ISSUE TITLE
Improve Excel compatibility

### ISSUE THREAD

**Issue by jferard** [jferard/fastods#216]
The goal of this issue is to follow the changes suggested by @ueen and discussed [here](https://github.com/jferard/fastods/pull/212).

**Comment by jferard** [comment]
@ueen: can you pull the last version and check if it works? I changed the name of the master page style and removed the empty `forms` tag.

**Comment by ueen** [comment]
Hey, i think you missed one crucial change
https://github.com/jferard/fastods/blob/bdb22d6389a1a09b91ad7a0ca8102f59ad77bab2/fastods/src/main/java/com/github/jferard/fastods/style/PageStyleBuilder.java line 126 the first parameter must also be 'Default' for the Document to be accepted by Excel, thanks for your work so far!

**Comment by jferard** [comment]
I still think it's possible to avoid to hard code the name. With the last version, I get:

 **`content.xml`**:

    <office:automatic-styles>
        ....
        <style:style style:name="ta1" style:family="table" style:master-page-name="Default"><style:table-properties table:display="true" style:writing-mode="lr-tb"/></style:style>
        ...
    </office:automatic-styles>

 **`styles.xml`**:

    <office:automatic-styles>
        ...
        <style:page-layout style:name="Default">...</style:page-layout>
    </office:automatic-styles>
    <office:master-styles>
        <style:master-page style:name="Default" style:page-layout-name="Default">
            ...
        </style:master-page>
    </office:master-styles>

That should do the trick. Can you confirm if Excel complains or not?

**Comment by ueen** [comment]
Oh sorry, didnt get that, great solution!

**Comment by ueen** [comment]
Excel doesnt complain anymore, great work, thanks a lot!!
Theres a small thing though, if a number is saved as string, excel displays a hint, saying so convert it to a number, ill make a suggestion via PR :)

**Comment by jferard** [comment]
Thanks for the feedback and your previous suggestions. I'm going to release the version 0.7.3 *very* soon (maybe today: would be available tomorrow on the maven repo).

About your last suggestion: I'd rather not pile up methods. But you can write your own function:

    class MyUtil {
        public static void setStringOrNumberValue(TableCell cell, String stringOrNumber) {
            try {
                Integer parse = Integer.parseInt(string);
                cell.setFloatValue(parse);
            } catch (NumberFormatException e) {
               cell.setStringValue(string);
           }
       }
    }

Usage:

        final TableCellWalker walker = table.getWalker();
        MyUtil.setStringOrNumberValue(walker, "foo");
        walker.next();
        MyUtil.setStringOrNumberValue(walker, "1");

If you are importing data from a CSV file, I'm working on a different method: https://github.com/jferard/fastods/issues/214

**Comment by ueen** [comment]
Alright, thanks i can do the evaluation before setting the value also, i just thought this might be a common issue and could be further developed into a setAutoValue maybe, that automatically detects the type for convenience, but i totally get that this might just be lazyness on my part that would clutter up the library :D so never mind - thanks for the quick replys you may close this issue as resolved :)

**Comment by ueen** [comment]
Another convenience method would be to create a sheet from a List (columns as fields from Objects) or a 2d string array, dont know if that would be something easy or useful to do, but i'm gonna put it outthere as something that i'd wish for
current solution looks like this

```
val data: MutableList<List<String>> = ArrayList()
    data.add(listOf("title1","title2","title3","title4","title5"))
    for (e in elements) {
        data.add(listOf(e.date,e.number,e.string,e.anotherString))
    }
    val file = File(...)

    val writer = OdsFactory.create().createWriter()
    val document = writer.document()
    val table = document.addTable(args.filmtitle)
    data.forEachIndexed { i, e ->
        e.forEachIndexed { iE, eE ->
            table.getRow(i).getOrCreateCell(iE).setStringValue(eE)
        }
    }
    writer.saveAs(file)
```

**Comment by ueen** [comment]
Just on final question, the setFloatValue ist really what i want it produces `value-type="float"` what i want is just `value-type="number"` what method do i have to call or could it be added for excel compatibility? :)

**Comment by ueen** [comment]
Never mind `value-type="number"` only works in Excel, not Libreoffice

**Comment by ueen** [comment]
Sorry to bother once more, theres an issue with setFloatValue or more specifically with `Default-_-float-data` it displays a number like this `1,00` but the actual value is `1` this means theres no way to save actual numbers?! 
Code used
`val parse: Number = eE.toInt()
                        cell.setFloatValue(parse)`
it only is displayed correctly after removing all `table:style-name="Default-_-float-data"` tags
maybe a setNumber method could be added without this tag in the final XML?

**Comment by jferard** [comment]
I'm trying to stick to the spec and there's nothing like an "integer" value type in OpenDocument spec: http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1417680_253892949.

You need to create your own `DataStyle`, like here: https://github.com/jferard/fastods/blob/master/fastods-examples/src/main/java/com/github/jferard/fastods/examples/D_SettingTheCellDataStyle.java#L82, with `decimalPlaces(0)`.

(Please open a new issue for a new question. )

**Comment by ueen** [comment]
Yea sorry, never mind, found the problem, see https://github.com/jferard/fastods/issues/217 and https://github.com/jferard/fastods/pull/218

**Comment by jferard** [comment]
I'm closing this issue for the moment. Many thanks to @ueen. Great help!
