### ISSUE TITLE
Symbol before number 

### ISSUE THREAD

**Issue by hyperhyena** [jferard/fastods#241]
I am implementing FastODS on my project. But I'm having an issue with formatted data being put into the document. 

![image](https://user-images.githubusercontent.com/46872213/156626088-dcc640ed-520e-4b32-9fca-ec7899bead37.png)

As you can see, when I click on the cell, the value is '100,0 instead of 100,0. That only happens to number values, and I imagine it has to do with the formatting I'm doing.

This is one of my formatted lines:

walker.setStringValue(String.format("%.1f", sumario.getPercentual(alternativaEmbrulhada) * 100));

I'm getting a result in percentage. I've tested the value insertion without being formatted and that weird symbol only shows up when I try formatting the value. Could it have anything to do with the FastODS library or is it something completely different?

**Comment by jferard** [comment]
Hi. You are dealing with a number (a percentage), but you are writing a string (`setStringValue`). It's not FastODS but LibreOffice itself that adds a quote to show that `100,0` is a text, not a number.
You could use `setFloatValue` or better, `setPercentageValue` (`1` means 100%). In your case:

    walker.setPercentageValue(sumario.getPercentual(alternativaEmbrulhada));

If you want to set the number of decimals to 1, this is a bit more complex: you have to configure the `PercentageStyle` of the `DataStyles` (see the tutorial).
