### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by juergen-albert** [jferard/fastods#246]
Dear @jferard,

we'd really love to use the project, as I already did in the past. I unfortunately noticed that is under GPL, which makes it unusable for most Projects, as GPL is incompatible with most other Licenses. The Original Project you forked from was under LGPL. Would you see a possibility to change it back to that? We would provide a PR that makes all the necessary changes if you would Agree.

**Comment by jferard** [comment]
Hello Jürgen.

Thanks for being interested in FastODS. I'm 100% sure the original project was under GPLv. 3. The sourceforge host states that the license is : "GNU Library or Lesser General Public License version 2.0 (LGPLv2)" (see https://sourceforge.net/projects/simpleods/), but when you download the last jar (0.5.3 - https://sourceforge.net/projects/simpleods/files/simpleods/0.5.3/), source files are included. Each of these source files has a header that reads:  

```
/*
*	SimpleODS - A lightweight java library to create simple OpenOffice spreadsheets
*    Copyright (C) 2008-2013 Martin Schulz <mtschulz at users.sourceforge.net>
*
*    This program is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
...   
```

I like the the principle of copyleft, but I can understand why you don't want to use a library under GPL. I hope you'll find another good library for generating ODS files, with a license that suits your needs !

**Comment by juergen-albert** [comment]
Thank you for the quick response. In this case there is nothing that can be done I guess.
