### ISSUE TITLE
Is there an example that shows how to set name for a cell?

### ISSUE THREAD

**Issue by parrotcar00** [jferard/fastods#251]
I want to create a named cell, I tried searching for an example in the repo but can't find it :(

I'm also unsure what attribute I might want to set on a cell that will set its name?

How do I set a cell's name?

**Comment by jferard** [comment]
Hi. No there is no example because this is not implemented :(. I'll have a look on how to add this (<table:named-range> 9.4.12 is ODS 1.3 spec).

**Comment by jferard** [comment]
References (Open Document Format for Office Applications (OpenDocument) Version 1.3. Part 3: OpenDocument Schema):
* `9.4.11. <table:named-expressions> `
* `9.4.12. <table:named-range>`

XML Sample:
```
              ...
        </table:table>
        <table:named-expressions>
             <table:named-range table:name="bar" table:base-cell-address="$Feuille2.$C$1" table:cell-range-address="$Feuille2.$C$1:.$D$3"/>
            <table:named-range table:name="foo" table:base-cell-address="$Feuille1.$A$1" table:cell-range-address="$Feuille1.$A$1:.$B$4"/>
        </table:named-expressions>
    </office:spreadsheet>
</office:body>
```

**Comment by jferard** [comment]
See: https://github.com/jferard/fastods/blob/master/fastods-examples/src/main/java/com/github/jferard/fastods/examples/H_AutofiltersAndDataPilotTables.java#L294.
