### ISSUE TITLE
[French] Conseils pour générations de fichiers ODS contenant 30.000 lignes

### ISSUE THREAD

**Issue by Max4409** [jferard/fastods#95]
Salut,

merci par avance pour le temps consacré sur ce sujet.
Le projet sur lequel je travaille nécessite de créer des centaines de fichiers ODS (certains contiennent presque 35.000 lignes). J'utilisais l'API odftoolkit au début mais les temps étaient catastrophiques !
Donc, déjà, bravo pour ce projet qui porte vraiment bien son nom.

Voici le code que j'utilise et qui fonctionne parfaitement. Je te sollicite juste pour me confirmer/infirmer la bonne utilisation de tes classes. Car je suis dans un délai court et je n'ai pas eu le temps de creuser à fond. 

final OdsFactory odsFactory = OdsFactory.create();
final AnonymousOdsFileWriter writer = odsFactory.createWriter();
final OdsDocument document = writer.document();
final Table table = document.addTable(nomTable, nbLigne, COLONNES.length);

final TableCellStyle styleEntete = TableCellStyle.builder("styleEntete").fontWeightBold().fontWrap(false)
            .backgroundColor(Color.GRAY80).borderAll(SimpleLength.mm(0.4), Color.BLACK, BorderAttribute.DEFAULT_STYLE).build();

// Création des entêtes
final TableRow row = table.nextRow();
for (int index = 0; index < COLONNES.length; index++)
{
    table.setColumnStyle(index, TableColumnStyle.builder("styleColonne" + index).columnWidth(
                SimpleLength.cm(Double.parseDouble(COLONNES[index][1]))).build());

     TableCell cell = row.getOrCreateCell(index);
     cell.setStringValue(COLONNES[index][0]);
     cell.setStyle(styleEntete);
}

final TableCellStyle styleTableau = TableCellStyle.builder("styleTableau").borderAll(SimpleLength.mm(0.15),
   Color.BLACK, BorderAttribute.DEFAULT_STYLE).build();

// Je boucle sur mes lignes 
final TableRow row = table.nextRow();
row.setDefaultCellStyle(styleTableau);
... Je valorise mes cellules ...

// Ajout des auto-filtre
document.addAutofilter(table, 0, 0, nbLigne - 1, COLONNES.length - 1);
// Sauvegarde du fichier
writer.saveAs(fichier);

**Comment by jferard** [comment]
Merci à toi de me faire un retour aussi sympathique. Je n'ai rien à dire : ça m'a l'air bon.
A noter que depuis le dernier commit (c9ddc90b711ada3e6bb4351d1deeafc601b45c25), il faut utiliser `SimpleColor.GRAY80` et `SimpleColor.BLACK`, car `Color` est devenu une interface.

**Comment by Max4409** [comment]
Ok ça marche, je vais modifier pour la couleur. j'ai 2 petites questions :

comme tu vois, je boucle sur les colonnes pour définir une largeur.
Il n'existe pas un seul paramètre niveau Table qui permettrait aux colonnes de s'ajuster automatiquement à la largeur de la cellule la plus grande qu'elle contient ?

Seconde question, le background-color est blanc par défaut. Ainsi les bordures des cellules n'apparaissent pas. Dans ODS, on peut définir "aucun remplissage" pour la couleur d'arrière plan.
Cette possibilité n'existe pas actuellement ?

**Comment by jferard** [comment]
Sur l'ajustement automatique, c'est en théorie possible, reste à savoir si LibreOffice le prend en compte selon la norme : j'ouvre une *issue* sur la question.
Sur le  background-color qui est blanc au niveau du style `TableCellStyle.DEFAULT_CELL_STYLE`, c'est un bug et j'ouvre également une *issue*.

**Comment by jferard** [comment]
J'ai pu régler un problème, celui de la grille (voir #97), mais l'autre relève de LibreOffice (voir #96). 
Une solution serait d'intégrer dans la boucle qui valorise les cellules un calcul de la largeur max par colonne (voir https://stackoverflow.com/a/258499/6914441 par ex.). Une fois toutes les cellules valorisées, il ne reste qu'à créer le style de colonne et à l'ajouter avec `table.setColumnStyle(<col>, <style>)`. L'idée est de ne boucler qu'une seule fois sur les lignes afin de ne pas perdre trop de temps et d'ajouter les styles à la fin.

**Comment by Max4409** [comment]
Ok super, merci pour ces infos.
Bonne continuation à toi.
Je ferme le sujet.
